Fix "TypeError: __init__() got an unexpected keyword argument 'stream'" on Python 2.6
"stream" argument used to be called "strm" in Python 2.6. Luckily, the
default value is "sys.stderr", so we don't need this argument at all.