Replace all dashes with dots in versioned provides and requires
e.g.:
mvn(org.codehaus.plexus:plexus-interactivity-api) = 1.0-alpha-6
will become:
mvn(org.codehaus.plexus:plexus-interactivity-api) = 1.0.alpha.6

This should prevent triggering of following error:
Error: Package: plexus-interactivity-jline-1.0-0.14.alpha6.10.fc22.noarch
    Requires: mvn(org.codehaus.plexus:plexus-interactivity-api) = 1.0-alpha-6
    Removing: plexus-interactivity-api-1.0-0.14.alpha6.9.fc22.noarch
        mvn(org.codehaus.plexus:plexus-interactivity-api) = 1.0-alpha-6
    Updated By: plexus-interactivity-api-1.0-0.14.alpha6.10.fc22.noarch
        mvn(org.codehaus.plexus:plexus-interactivity-api) = 1.0-alpha-6